language: python

python:
  - 2.7

services: postgresql

env:
  global:
  - DJANGO_SETTINGS_MODULE="letter_analys.settings"
  - PYTHONPATH=$HOME/builds/devBibin/letter_analys
  - PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:
  - bash run_script.sh

deploy:
  skip_cleanup: true
  provider: heroku
  app : grim-wizard-85961
  api_key:
    secure: "c03860e0-11c9-44e1-853b-5320da4bef05"

notifications:
  email: false
